In [14]:
import numpy as np
import pandas as pd
import requests

In [7]:
url = "https://fantasy.premierleague.com/api/bootstrap-static/"

response = requests.get(url)

json = response.json()

json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [46]:
elements_df = pd.DataFrame(json['elements'])
elements_df.columns

Index(['chance_of_playing_next_round', 'chance_of_playing_this_round', 'code',
       'cost_change_event', 'cost_change_event_fall', 'cost_change_start',
       'cost_change_start_fall', 'dreamteam_count', 'element_type', 'ep_next',
       'ep_this', 'event_points', 'first_name', 'form', 'id', 'in_dreamteam',
       'news', 'news_added', 'now_cost', 'photo', 'points_per_game',
       'second_name', 'selected_by_percent', 'special', 'squad_number',
       'status', 'team', 'team_code', 'total_points', 'transfers_in',
       'transfers_in_event', 'transfers_out', 'transfers_out_event',
       'value_form', 'value_season', 'web_name', 'minutes', 'goals_scored',
       'assists', 'clean_sheets', 'goals_conceded', 'own_goals',
       'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards',
       'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat',
       'ict_index', 'influence_rank', 'influence_rank_type', 'creativity_rank',
       'creativity_rank_type', 'threat_rank', 'threat_rank_type',
       'ict_index_rank', 'ict_index_rank_type',
       'corners_and_indirect_freekicks_order',
       'corners_and_indirect_freekicks_text', 'direct_freekicks_order',
       'direct_freekicks_text', 'penalties_order', 'penalties_text'],
      dtype='object')

In [45]:
events_df = pd.DataFrame(json['events'])
events_df.columns

Index(['id', 'name', 'deadline_time', 'average_entry_score', 'finished',
       'data_checked', 'highest_scoring_entry', 'deadline_time_epoch',
       'deadline_time_game_offset', 'highest_score', 'is_previous',
       'is_current', 'is_next', 'chip_plays', 'most_selected',
       'most_transferred_in', 'top_element', 'top_element_info',
       'transfers_made', 'most_captained', 'most_vice_captained'],
      dtype='object')

In [40]:
elements_df = pd.DataFrame(json['elements'])
elements_types_df = pd.DataFrame(json['element_types'])
teams_df = pd.DataFrame(json['teams'])

elements_types_df.columns
teams_df

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,...,None,False,0,1190,1220,1110,1140,1100,1170,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,...,None,False,0,1130,1180,1130,1140,1130,1160,2
2,94,0,None,3,0,Brentford,0,0,0,BRE,...,None,False,0,1080,1100,1090,1130,1100,1150,130
3,36,0,None,4,0,Brighton,0,0,0,BHA,...,None,False,0,1140,1180,1140,1180,1090,1130,131
4,90,0,None,5,0,Burnley,0,0,0,BUR,...,None,False,0,1050,1060,1050,1070,1060,1100,43
5,8,0,None,6,0,Chelsea,0,0,0,CHE,...,None,False,0,1340,1350,1320,1350,1340,1320,4
6,31,0,None,7,0,Crystal Palace,0,0,0,CRY,...,None,False,0,1060,1100,1100,1140,1090,1120,6
7,11,0,None,8,0,Everton,0,0,0,EVE,...,None,False,0,1190,1230,1140,1150,1150,1210,7
8,13,0,None,9,0,Leicester,0,0,0,LEI,...,None,False,0,1170,1190,1100,1120,1120,1160,26
9,2,0,None,10,0,Leeds,0,0,0,LEE,...,None,False,0,1090,1130,1050,1060,1110,1150,9
10,14,0,None,11,0,Liverpool,0,0,0,LIV,...,None,False,0,1340,1350,1290,1330,1350,1360,10
11,43,0,None,12,0,Man City,0,0,0,MCI,...,None,False,0,1340,1360,1330,1350,1340,1350,11
12,1,0,None,13,0,Man Utd,0,0,0,MUN,...,None,False,0,1280,1320,1200,1240,1250,1300,12
13,4,0,None,14,0,Newcastle,0,0,0,NEW,...,None,False,0,1050,1070,1030,1040,1100,1140,23
14,45,0,None,15,0,Norwich,0,0,0,NOR,...,None,False,0,1010,1030,1000,1020,1000,1040,14
15,20,0,None,16,0,Southampton,0,0,0,SOU,...,None,False,0,1070,1090,1090,1120,1090,1100,20
16,6,0,None,17,0,Spurs,0,0,0,TOT,...,None,False,0,1180,1210,1110,1130,1120,1170,21
17,57,0,None,18,0,Watford,0,0,0,WAT,...,None,False,0,1050,1060,1040,1060,1040,1050,33
18,21,0,None,19,0,West Ham,0,0,0,WHU,...,None,False,0,1240,1250,1120,1140,1260,1280,25
19,39,0,None,20,0,Wolves,0,0,0,WOL,...,None,False,0,1090,1100,1100,1120,1090,1120,38

In [54]:
slim_elements_df = elements_df[['second_name', 'team', 'element_type', 'selected_by_percent', 'now_cost', 'minutes', 'value_season','transfers_in']]



slim_elements_df.now_cost = slim_elements_df.now_cost/10
slim_elements_df

slim_elements_df['position'] = slim_elements_df.element_type.map(elements_types_df.set_index('id').singular_name)
slim_elements_df['teams'] = slim_elements_df.team.map(teams_df.set_index('id').name)

C:\Users\Emmanuel\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
C:\Users\Emmanuel\AppData\Local\Temp/ipykernel_24912/3424571342.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  slim_elements_df['position'] = slim_elements_df.element_type.map(elements_types_df.set_index('id').singular_name)
C:\Users\Emmanuel\AppData\Local\Temp/ipykernel_24912/3424571342.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  slim_elements_df['teams'] = slim_elements_df.team.map(teams_df.set_index('id').name)
C:\Users\Emmanuel\AppData\Local\Temp/ipykernel_24912/3424571342.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  slim_elements_df.sort_values('value_season', ascending= False, inplace= True)

,second_name,team,element_type,selected_by_percent,now_cost,minutes,value_season,transfers_in,position,teams
487,Lloris,17,1,9.5,5.5,630,6.4,690368,Goalkeeper,Spurs
413,Manquillo,14,2,9.1,4.0,315,3.2,375925,Defender,Newcastle
180,Mount,6,3,8.8,7.4,331,2.2,448253,Midfielder,Chelsea
326,Ramses Becker,11,1,8.8,6.0,630,5.8,361701,Goalkeeper,Liverpool
69,Jansson,3,2,8.5,4.6,621,8.3,791896,Defender,Brentford
...,...,...,...,...,...,...,...,...,...,...
123,Scherpen,4,1,0.0,4.5,0,0.0,1410,Goalkeeper,Brighton
113,Fernandes Da Silva Junior,4,2,0.0,4.0,0,0.0,0,Defender,Brighton
112,Jahanbakhsh,4,3,0.0,5.5,0,0.0,0,Midfielder,Brighton
53,Guilbert,2,2,0.0,4.5,0,0.0,449,Defender,Aston Villa
540,Ngakia,18,2,0.0,4.4,183,0.9,842,Defender,Watford