In [33]:
import requests
import numpy as np
import pandas as pd

In [34]:
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'

r = requests.get(url)

In [35]:
json = r.json()

In [36]:
json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [37]:
teams = pd.DataFrame(json['teams'])
teams

,code,draw,form,id,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,4,None,False,0,1200,1250,1130,1150,1220,1210,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,3,None,False,0,1100,1160,1120,1140,1080,1100,2
2,94,0,None,3,0,Brentford,0,0,0,BRE,2,None,False,0,1010,1020,1020,1030,1020,1030,130
3,36,0,None,4,0,Brighton,0,0,0,BHA,3,None,False,0,1100,1130,1150,1190,1100,1130,131
4,90,0,None,5,0,Burnley,0,0,0,BUR,2,None,False,0,1060,1070,1040,1090,1040,1080,43
5,8,0,None,6,0,Chelsea,0,0,0,CHE,4,None,False,0,1250,1280,1260,1300,1250,1310,4
6,31,0,None,7,0,Crystal Palace,0,0,0,CRY,3,None,False,0,1090,1090,1030,1120,1010,1020,6
7,11,0,None,8,0,Everton,0,0,0,EVE,3,None,False,0,1250,1130,1130,1100,1200,1140,7
8,13,0,None,9,0,Leicester,0,0,0,LEI,4,None,False,0,1240,1180,1190,1150,1150,1230,26
9,2,0,None,10,0,Leeds,0,0,0,LEE,3,None,False,0,1160,1170,1060,1150,1210,1170,9
10,14,0,None,11,0,Liverpool,0,0,0,LIV,4,None,False,0,1250,1260,1190,1210,1300,1230,10
11,43,0,None,12,0,Man City,0,0,0,MCI,5,None,False,0,1340,1360,1280,1320,1340,1350,11
12,1,0,None,13,0,Man Utd,0,0,0,MUN,4,None,False,0,1250,1320,1250,1280,1240,1310,12
13,4,0,None,14,0,Newcastle,0,0,0,NEW,2,None,False,0,1050,1070,1050,1060,1030,1110,23
14,45,0,None,15,0,Norwich,0,0,0,NOR,2,None,False,0,1020,1030,1030,1040,1020,1030,14
15,20,0,None,16,0,Southampton,0,0,0,SOU,3,None,False,0,1060,1100,1030,1110,1110,1160,20
16,6,0,None,17,0,Spurs,0,0,0,TOT,4,None,False,0,1190,1250,1130,1170,1250,1290,21
17,57,0,None,18,0,Watford,0,0,0,WAT,2,None,False,0,1020,1030,1030,1050,1010,1040,33
18,21,0,None,19,0,West Ham,0,0,0,WHU,4,None,False,0,1150,1260,1140,1190,1260,1290,25
19,39,0,None,20,0,Wolves,0,0,0,WOL,3,None,False,0,1080,1110,1120,1130,1040,1120,38

In [38]:
pd.options.display.max_columns = None

In [39]:
elements_df = pd.DataFrame(json['elements'])
elements_df

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,NaN,NaN,80201,0,0,-1,1,0,1,2.3,0.8,1,Bernd,1.3,1,False,,None,49,80201.jpg,1.3,Leno,1.8,False,None,a,1,3,4,15223,7432,56805,8639,0.3,0.8,Leno,270,0,0,0,9,0,0,0,0,0,9,0,48,79.0,0.0,0.0,7.9,41,6,484,50,455,48,161,7,NaN,,NaN,,NaN,
1,100.0,100.0,115918,0,0,0,0,0,1,1.0,-0.5,0,Rúnar Alex,0.0,2,False,,2021-08-20T09:30:14.051083Z,40,115918.jpg,0.0,Rúnarsson,1.5,False,None,a,1,3,0,18331,8046,14908,2734,0.0,0.0,Rúnarsson,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,353,33,342,16,287,13,363,33,NaN,,NaN,,NaN,
2,0.0,50.0,47431,0,0,-2,2,0,3,0.0,-0.2,0,Willian,0.0,3,False,Transferred to Corinthians,2021-08-20T09:30:14.065783Z,63,47431.jpg,0.0,Borges Da Silva,0.1,False,None,u,1,3,0,914,50,15520,1570,0.0,0.0,Willian,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,575,235,575,236,572,235,576,236,4.0,,2.0,,NaN,
3,100.0,100.0,54694,0,0,-1,1,0,4,1.7,0.2,1,Pierre-Emerick,0.7,4,False,,2021-08-13T14:30:14.477664Z,99,54694.jpg,1.0,Aubameyang,1.3,False,None,a,1,3,2,26000,13177,139227,9292,0.1,0.2,Aubameyang,87,0,0,0,4,0,0,0,0,0,0,0,5,5.0,2.7,19.0,2.6,286,31,253,35,144,31,271,34,NaN,,NaN,,1.0,
4,NaN,NaN,58822,0,0,-1,1,0,2,1.0,-0.5,-1,Cédric,0.0,5,False,,None,44,58822.jpg,0.0,Soares,0.2,False,None,a,1,3,0,3061,981,7718,1622,0.0,0.0,Cédric,180,0,0,0,7,0,0,0,1,0,0,0,16,21.4,21.8,0.0,4.3,202,84,143,35,323,121,227,80,NaN,,5.0,,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,0.0,0.0,209353,0,0,0,0,0,4,0.0,0.0,0,Patrick,0.0,523,False,Season long loan to Empoli,2021-08-15T12:06:51.809579Z,50,209353.jpg,0.0,Cutrone,0.1,False,None,u,20,39,0,1047,0,11721,968,0.0,0.0,Cutrone,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,521,62,520,64,503,59,527,65,NaN,,NaN,,NaN,
580,NaN,NaN,245923,0,0,0,0,0,3,0.5,-0.5,0,Luke,0.0,547,False,,None,45,245923.jpg,0.0,Cundle,0.0,False,None,a,20,39,0,2618,937,1214,437,0.0,0.0,Cundle,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,467,179,461,183,428,167,472,182,NaN,,NaN,,NaN,
581,NaN,NaN,461026,0,0,0,0,0,3,0.5,-0.5,0,Chem,0.0,548,False,,None,45,461026.jpg,0.0,Campbell,0.2,False,None,a,20,39,0,12653,3920,5206,1746,0.0,0.0,Campbell,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,477,184,471,188,439,173,482,187,NaN,,NaN,,NaN,
582,NaN,NaN,481626,0,0,0,0,0,2,0.5,-0.5,0,Christian,0.0,549,False,,None,40,481626.jpg,0.0,Marques,0.4,False,None,a,20,39,0,18361,5247,5813,1867,0.0,0.0,Marques,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,378,137,367,138,315,113,388,139,NaN,,NaN,,NaN,
583,NaN,NaN,184754,0,0,0,0,0,4,2.1,1.1,0,Hee-Chan,0.0,583,False,,None,55,184754.jpg,0.0,Hwang,0.0,False,None,a,20,39,0,2261,2261,285,285,0.0,0.0,Hwang,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,557,71,558,73,550,69,562,74,NaN,,NaN,,NaN,

In [52]:
players_fixtures = pd.DataFrame(elements_df['id'])
players_fixtures['player_name'] = elements_df['first_name'] + '  ' + elements_df['second_name']
players_fixtures['player_code'] = elements_df['code']
players_fixtures['player_id'] = elements_df['id']

#for x in players_fixtures['player_code'][0:1]:
    #fixture_url = f'https://fantasy.premierleague.com/api/element-summary/{x}/'
    #r_fix = requests.get(fixture_url)
    #f_json = r_fix.json()
    #fixtures = pd.DataFrame(f_json['fixtures'])

    #team _a
    #fixtures['team_versus'] = fixtures.team_a.map(teams.set_index('id').name)
    #fixtures['player_id'] = players_fixtures['player_id']

players_fixtures['team_code'] = players_fixtures.player_code.map(elements_df.set_index('code').team_code)
players_fixtures['team'] = players_fixtures.team_code.map(teams.set_index('code').name)
#players_fixtures

for x in players_fixtures['player_id'][0:1]:
    fixture_url = f'https://fantasy.premierleague.com/api/element-summary/{x}/'
    r_fix = requests.get(fixture_url)
    f_json = r_fix.json()

    fixtures = pd.DataFrame(f_json['fixtures'])

    fixtures['team_versus'] = fixtures.team_a.map(teams.set_index('id').name)
    #a = fixtures.team_a
    #if (a > 1).bool() :
        #fixtures['team_versus'] = fixtures.team_a.map(teams.set_index('id').name)
    #else :
        #ffixtures['team_versus'] = fixtures.team_h.map(teams.set_index('id').name)
##players_fixtures['fixtures'] =fixtures['team_versus']
#players_fixtures

In [56]:
fixtures['player_name'] = elements_df['first_name'] + ' '+ elements_df['second_name']

fixtures #use a crosstab

df1 = fixtures[['event_name', 'team_versus', 'player_name']]

fixture_ticker = pd.pivot_table(df1, index = 'player_name', values ='team_versus', columns pi= 'event_name')

fixture_ticker

DataError: No numeric types to aggregate

In [57]:

slim_fixtures_df =pd.pivot_table(df1, columns = 'event_name', index ='player_name', values = 'team_versus')

#slim_fixtures_df

DataError: No numeric types to aggregate

NameError: name 'fixtures' is not defined