In [47]:
#utils 
import pandas as pd

In [48]:
file = "2021_player_data"

with open(file, 'r') as input:
    data = pd.read_csv(input)

pd.options.display.max_columns = None
data

,Unnamed: 0,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,0,100.0,100.0,80201,0,0,-5,5,1,1,1.0,0.5,0,Bernd,0.0,1,False,NaN,2022-02-11T08:00:15.144286Z,45,80201.jpg,2.5,Leno,0.8,False,NaN,a,1,3,10,80974,0,205566,0,0.0,2.2,Leno,360,0,0,1,9,0,0,0,0,0,10,0,69,85.0,0.0,0.0,8.5,406,29,618,69,601,60,443,30,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.0,0.0,115918,0,0,0,0,0,1,0.0,0.0,0,Rúnar Alex,0.0,2,False,Joined OH Leuven on a season-long loan - Expec...,2021-08-31T22:00:09.069158Z,40,115918.jpg,0.0,Rúnarsson,0.5,False,NaN,u,1,3,0,19017,0,81363,0,0.0,0.0,Rúnarsson,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,540,55,527,34,494,19,545,55,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.0,0.0,47431,0,0,-2,2,0,3,0.0,0.0,0,Willian,0.0,3,False,Transferred to Corinthians,2021-08-20T09:30:14.065783Z,63,47431.jpg,0.0,Borges Da Silva,0.1,False,NaN,u,1,3,0,914,0,20541,0,0.0,0.0,Willian,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,733,307,733,307,733,307,733,307,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.0,0.0,54694,0,0,-4,4,0,4,0.0,0.0,0,Pierre-Emerick,0.0,4,False,Left club by mutual consent,2022-02-02T08:21:28.428217Z,96,54694.jpg,3.1,Aubameyang,1.2,False,NaN,u,1,3,44,742898,0,900060,0,0.0,4.6,Aubameyang,1036,4,1,6,16,0,0,2,3,0,0,7,131,217.6,132.4,582.0,92.9,301,37,260,40,61,27,182,33,NaN,NaN,NaN,NaN,NaN,NaN
4,4,100.0,100.0,58822,0,0,-3,3,1,2,2.2,14.5,14,Cédric,14.0,5,False,NaN,2022-01-13T23:00:13.573747Z,42,58822.jpg,2.3,Soares,0.4,False,NaN,a,1,3,48,66997,0,55154,0,3.3,11.4,Cédric,1481,1,1,3,27,0,0,0,3,0,0,3,292,318.4,327.1,111.0,75.8,234,89,127,25,290,87,232,69,2.0,NaN,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,732,0.0,0.0,428610,0,0,0,0,0,3,0.0,0.0,0,Bruno André,0.0,661,False,Season-long loan to Grasshopper Club Zurich,2022-02-03T09:42:10.046668Z,45,428610.jpg,0.0,Cavaco Jordão,0.0,False,NaN,u,20,39,0,612,0,546,0,0.0,0.0,Jordão,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,655,258,653,260,640,258,658,259,NaN,NaN,NaN,NaN,NaN,NaN
733,733,NaN,NaN,510362,0,0,-1,1,0,2,-0.6,0.0,1,Toti António,1.0,685,False,NaN,NaN,44,510362.jpg,1.5,Gomes,0.0,False,NaN,a,20,39,6,696,0,558,0,0.2,1.4,Toti,360,0,0,0,6,0,0,0,1,0,0,0,52,87.0,4.5,28.0,12.0,403,155,451,168,389,145,424,156,NaN,NaN,NaN,NaN,NaN,NaN
734,734,0.0,0.0,225000,0,0,0,0,0,2,0.0,0.0,0,Dion,0.0,686,False,Joined QPR on loan until the end of the season...,2022-01-25T23:30:21.214543Z,40,225000.jpg,0.0,Sanderson,0.0,False,NaN,u,20,39,0,241,0,196,0,0.0,0.0,Sanderson,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,551,202,539,201,506,194,556,202,NaN,NaN,NaN,NaN,NaN,NaN
735,735,0.0,0.0,232351,0,0,0,0,0,3,0.0,0.0,0,Ryan,0.0,687,False,Joined Blackburn Rovers on loan until the end ...,2022-02-01T00:30:12.329095Z,45,232351.jpg,0.0,Giles,0.0,False,NaN,u,20,39,0,86,0,62,0,0.0,0.0,Giles,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,646,253,642,255,629,253,648,254,NaN,NaN,NaN,NaN,NaN,NaN
736,736,NaN,NaN,510363,0,0,0,0,0,3,1.4,-1.0,0,Francisco Jorge,0.0,689,False,NaN,NaN,55,510363.jpg,2.5,Tomás Oliveira,0.0,False,NaN,a,20,39,20,2256,0,1393,0,0.0,3.6,Chiquinho,203,0,3,0,5,0,0,0,0,0,0,2,67,99.4,83.4,118.0,30.1,390,164,308,166,284,147,366,165,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
column_new = data[['code','element_type','id', 'first_name',
       'now_cost', 'points_per_game', #'team',
       'team_code', 'total_points', 
       #'value_form', 
       'value_season',
       'minutes', 'goals_scored', 'assists', 'clean_sheets',
       #'goals_conceded', 'penalties_saved', 'penalties_missed',
       #'yellow_cards', 'red_cards', 'saves', 
       'bonus', 'bps', 'influence',
       'creativity', 'threat', 'direct_freekicks_order',
       'penalties_order' ]]
column_new = column_new.fillna(0)

gk_df = column_new[column_new.element_type ==1]
defender_df = column_new[column_new.element_type ==2 ]
mid_df = column_new[column_new.element_type ==3 ]
striker_df = column_new[column_new.element_type ==4 ]

In [84]:
max(striker_df['penalties_order'])

X_features = mid_df['points_per_game', ]

4.0

Cluster players to determine position. use heatmap to determine average position

Create model based on old data, using difference between old price and new price and season performance

In [85]:
mid_df

,code,element_type,id,first_name,now_cost,points_per_game,team_code,total_points,value_form,value_season,minutes,goals_scored,assists,clean_sheets,bonus,bps,influence,creativity,threat,direct_freekicks_order,penalties_order
2,47431,3,3,Willian,63,0.0,3,0,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
6,84450,3,7,Granit,48,2.2,3,60,0.4,12.5,2327,1,2,6,3,334,395.4,522.9,262.0,4.0,0.0
10,153256,3,12,Mohamed Naser,44,1.9,3,27,0.5,6.1,801,0,2,0,0,156,163.2,131.5,49.0,0.0,0.0
11,154043,3,13,Ainsley,52,1.5,3,12,0.0,2.3,263,0,0,2,0,44,42.6,41.3,9.0,0.0,0.0
13,167199,3,15,Thomas,50,3.0,3,71,0.0,14.2,2027,2,2,10,4,345,359.6,275.5,394.0,6.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,245923,3,547,Luke,44,1.8,39,7,0.0,1.6,179,0,0,1,0,32,17.0,32.0,2.0,0.0,0.0
726,461026,3,548,Chem,44,1.0,39,1,0.0,0.2,12,0,0,0,0,5,2.0,1.7,2.0,0.0,0.0
732,428610,3,661,Bruno André,45,0.0,39,0,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
735,232351,3,687,Ryan,45,0.0,39,0,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
736,510363,3,689,Francisco Jorge,55,2.5,39,20,0.0,3.6,203,0,3,0,2,67,99.4,83.4,118.0,0.0,0.0